version: '2.34.0-desktop.1'
services:
  db:
    image: postgres:17
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      POSTGRES-DB: ${DB}
    ports:
      - "5432:5432"
  api:
    build: .
    ports:
      - "9090:9090"
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
    depends_on:
      - db