version: '2.34.0-desktop.1'
services:
  db:
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - "5432:5432"
  api:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      - db